### ISSUE TITLE
Parse dynamic imports with backticks

### ISSUE THREAD

**Issue by bluwy** [guybedford/es-module-lexer#118]
When parsing a dynamic import with backticks, the `s` and `e` result can be used to get the raw string. However the `e` result seems to always be one index less of the closing parenthesis/comma, instead of the last backtick. 

# Reproduction

[Stackblitz](https://stackblitz.com/edit/node-gjj4bq?file=index.js)

Run `node index.js` in the terminal to log the first parsed import

# Expected result

The log should be ```"`bla.js`"```

# Actual result

It gives ```"`bla.js`\n  /* bar */\n"``` (trailing comments aren't stripped)

**Comment by guybedford** [comment]
@bluwy I agree it would be nice to add this trailing whitespace / comment adjustment to the output. This isn't so much a bug though since arbitrary dynamic import expressions just are considered as arbitrary code expressions and the handling of whitespace and comments is thus somewhat of an implementation detail. I will leave this open to track any improvement here as a feature.
