### ISSUE TITLE
Parsing `vscode-uri` ESM file returns nothing

### ISSUE THREAD

**Issue by alex-kinokon** [guybedford/es-module-lexer#153]
Parsing [vscode-uri/lib/esm/index.js](https://unpkg.com/vscode-uri@3.0.7/lib/esm/index.js) which ends in `export const{URI,Utils}=LIB` gives `imports: [], exports: []`.

**Comment by guybedford** [comment]
This is because this library doesn't support full syntax parsing of arbitrary destructuring and variable declarations, see the limitations section.

That said, I've put together some initial prototyping of simple destructuring for a case like this in https://github.com/guybedford/es-module-lexer/pull/154.

**Comment by guybedford** [comment]
1.3.0 is now released with simple destructuring support, that should resolve this case.
