### ISSUE TITLE
Streaming API

### ISSUE THREAD

**Issue by guybedford** [guybedford/es-module-lexer#38]
In line with https://github.com/guybedford/es-module-shims/issues/64, trying to figure out how a streaming API might work.

From an API perspective, it is very straightforward to just implement a `streamEnd < sourceEnd` on which computation should stop, while retaining the parser state variables to be able to resume from the same point again easily. Any imports / exports read while stopped should ideally be popped to allow multiple batches of import/export reads.

The main issue with a streaming API is that we may have to effectively be parsing multiple modules simultaneously. The simpler model for this may actually be to have a pool of instantiated parsers exposed instead of trying to handle the pooling within the Wasm memory itself.

That means the overall API may need to change to expose `createParser()` over `parse()`.

Eg:

```js
const createParser = require('es-module-lexer');

(async () => {
  const parser1 = await createParser();
  const parser2 = await createParser();

  // second argument to parse is total length
  const stream = parser1('export var p = 5', 1000);
  // allows successive streams of string | ArrayBuffer
  var [imports, exports] = stream('; export var q = 6');
  // exports[0] === p;
  // empty stream implies end
  var [imports, exports] = stream();
  // exports[0] === q;
})();
```

It's a little bit of work so should be demonstrated to be worth the effort though.

**Comment by TomerAberbach** [comment]
Streaming support would be cool. Maybe I don't fully understand your motivation, but what would you think of returning a lazy iterator/iterable over the imports/exports? You could provide either an import or export at each iteration:
```js
for (const { type, ...rest } of await parse(code)) {
  if (type === 'import') {
    // process import (`rest`), maybe break early to avoid processing all of the code
  } else {
    // process export (`rest`), maybe break early to avoid processing all of the code
  }
}
```

Or in more of your style:
```js
const iterator = await parse(code)
const importOrExport1 = iterator.next().value
const importOrExport2 = iterator.next().value
// ...
```

I'd be interested in helping out so let me know what you think!

**Comment by guybedford** [comment]
Hi @TomerAberbach glad to hear you find this work interesting :)

So the main feature of streaming I was considering was to allow eager parsing of the network stream of the incoming source for network applications. The idea being that it could in theory be a performance benefit, while also forming a sort of a way to parallelize work in allowing tasks to happen between stream segments.

Whether that would actually work out is another question though entirely, and it could be quite complex to pull off, including the memory work to possibly allow multiple in-flight parallel operations in the same wasm memory.

Hope that helps to understand the motivations, the thing this needs to be balanced again is that switching between JS and Wasm will incur a performance penalty such that any streaming work has actually has a very real possibility of making this project slower.

What sort of use cases did you have in mind here?

**Comment by TomerAberbach** [comment]
I didn't have a very specific use case in mind. I was thinking that generally it would be useful to lazily iterate over (and process) the imports and exports. Additionally, if you're looking for a specific import or export, then lazily iterating would allow you to stop early once you find it. Also, returning an iterable is nice because it would allow users who want an array to obtain it like so: `[...(await parse(code))]`.

I guess supporting your use case would require more than just returning a lazy iterable/iterator. It would also require allowing a stream or string iterable/iterator as input rather than the whole code string.

I definitely understand the concern around switching between JS and WASM frequently. To be honest, I don't have a lot of experience with WASM so I'm not sure if it would totally degrade performance.

**Comment by TomerAberbach** [comment]
@guybedford I wrote a [thin wrapper around this package](https://github.com/TomerAberbach/parse-imports) that provides information about imports in a more structured format. Currently it lazily processes each import, but because there's no streaming API yet it has to get the full array of imports before lazily processing each one of them. So if there was a streaming API, then I'd be able to not only lazily process the imports, but do it without buffering them all first.
