### ISSUE TITLE
Support JSX

### ISSUE THREAD

**Issue by FredKSchott** [guybedford/es-module-lexer#47]
@guybedford We have a feature request from Snowpack-land that I'm curious to hear your take on.

In the past we've used es-module-lexer so that Snowpack can scan imports from your JS app. This works fine for normal JS apps and even TypeScript apps. But, if you write with JSX, es-module-lexer will fail with a parse error, and you end up having to run the scanner on the final built JS directory instead of your `src/` directory. 

```
export default () => <div></div>;
// Parse error @:1:34
```

Some users have requested that we add basic support for JSX (https://www.pika.dev/npm/snowpack/discuss/91) and we wanted to enable this for our users if we could. 

Is JSX something that you're interested in supporting inside of es-module-lexer? If so, I can look deeper into how that might work within es-module-lexer itself and hopefully provide a PR. If not, I'll see if there's some way that we could strip JSX from each string on our end before passing it into es-module-lexer.

**Comment by guybedford** [comment]
Hi @FredKSchott so I must admit I'm not sure this is completely straightforward, because it relies on knowing when the ECMAScript parser is in the PrimaryExpression state which is not something this project tracks. In addition we would have to carefully handle the full state transitions of the entire JSX grammar as described in https://facebook.github.io/jsx/. I think combined that would result in quite a bit of overhead to support something which is not a primary goal of this project.

I mean, sure, adding special support for `</` to just "not throw" may make it sort of work, but this project needs to parse valid grammar with 100% accuracy so I wouldn't want to weaken any of those guarantees.

A preprocessing step specific to JSX sounds sensible to me. If you can prove there is a small implementation with 100% accuracy then I'd gladly support it, but I don't think it is possible on a brief look at the current requirements, especially since this project does not support the ES6 cover grammars necessary for comprehensive primary expression detection as it is not a parser.

**Comment by FredKSchott** [comment]
Hey Guy, thanks for the reply and sorry for the slow response. That makes total sense to me, I'll look into what I can do inside of Snowpack to compile out the JSX before passing it to es-module-lexer. 

Feel free to close.
