### ISSUE TITLE
Acorn / Esprima integrations

### ISSUE THREAD

**Issue by privatenumber** [guybedford/es-module-lexer#49]
Really cool to see WASM used to make such a huge improvement on a foundational aspect of parsing.

I'm wondering if there are any plans to integrate this to popular parsers like Acorn or Espirma. Considering they're used by popular tools like Webpack and ESLint, I imagine it would make a very high performance impact across the JS ecosystem.

**Comment by guybedford** [comment]
This isn't a parser so can't even do eg scope analysis. It's fast because it focuses on solving just the problem we needed to solve here of parsing module syntax only, and correctly.

The future of JS optimization is certainly tooling which is native and compiles to WASM. esbuild is a start towards this but it will likely take a few attempts to get to the level of flexibility in architecture of JS build tools today.

My go-to fun project for the past while has been a Zig-based port of Acorn. This stuff is really fun to work on - the explosion of "wow wasm" in the JS land for tooling will likely continue as more "native" engineers see the potential. My own project probably won't see the light of day anytime soon - it's still not even compiling (started out a a C++ port which was working fine before I decided that was too high level and started rewriting it all in Zig), I'm probably a few months off it working, since it's an evening a month project. Higher priorities like jspm3.

There is likely also low hanging fruit in running emscripten against existing rust projects etc.

The long-term future of JS tooling will certainly not be JS-based, since the perf win is just too much. But don't underestimate how long it will take to get there :)
