### ISSUE TITLE
Parse Error: increment operator & division

### ISSUE THREAD

**Issue by FredKSchott** [guybedford/es-module-lexer#50]
As seen in: https://unpkg.com/canvas-confetti@1.2.0/src/confetti.js

```js
x++ / 42; // Parse Error
x-- / 42; // Parse Error
(x++) / 42; // Parse Error
++x / 42; // OK
--x / 42; // OK
x++ * 42; // OK
x++ + 42; // OK
x++ - 42; // OK
```

I wasn't able to tell where the error might be coming from in the code, but hopefully these test cases point in the right direction.

**Comment by guybedford** [comment]
@FredKSchott I just posted a fix in https://github.com/guybedford/es-module-lexer/commit/5b56821041b67c1501b6da104cc74083b0e00ba1.

npm seems to be having publishing issues right now.... so I can't publish the fix. Will keep this open until its out at least to notify you there.

Otherwise, the wasm is checked in so running `yarn build` only will get the `dist` files going.

**Comment by FredKSchott** [comment]
Awesome, thanks for the quick fix.

**Comment by guybedford** [comment]
Finally got to publishing this - just let me know if you see any further issues!
