### ISSUE TITLE
Parse error on string concat

### ISSUE THREAD

**Issue by drwpow** [guybedford/es-module-lexer#60]
Hello! Thanks for such an incredible library. Don’t know what we would do without it!

I am running into a problem with the latest version of `react-redux`. Specifically [this line](https://github.com/reduxjs/react-redux/blob/master/src/hooks/useSelector.js#L42):

```js
      err.message += `\nThe error may be correlated with this previous error:\n${latestSubscriptionCallbackError.current.stack}\n\n`
```

To be clear, this works just fine. However, when running this through Rollup for older browsers, the alternate method of string concatenation does throw a parse error:

```js
      err.message += "\nThe error may be correlated with this previous error:\n" + latestSubscriptionCallbackError.current.stack + "\n\n";
```

To confirm, I tried running the following test in `_unit.cjs`:

```js
  test('String concatenation', () => {
    const [imports, exports] = parse(`err.message += "\nThe error may be correlated with this previous error:\n" + latestSubscriptionCallbackError.current.stack + "\n\n";`)
    assert.equal(imports.length, 0);
    assert.equal(exports.length, 0);
  })
```

And got this error:

```
  41 passing (27ms)
  1 failing

  1) Lexer
       String concatenation:
     Error: Parse error @:1:17
```

Anyway I wanted to open up a discussion about this first. Happy to look into the issue more, or try my hand at submitting a PR to fix this, though the C code looks a little intimidating to me 😅 .

Thanks again for all your time put into this!

**Comment by guybedford** [comment]
Hey @drwpow glad it's working well for you and always happy to help here.

So the case seems like it's a correct failure to me in the above, because the check:

```js
parse(`err.message += "\nThe error may be correlated with this previous error:\n" + latestSubscriptionCallbackError.current.stack + "\n\n";`)
```

would actually see the JS source string as using real newlines, without the `\`, and newlines aren't valid in strings.

This may be some escaping thing where before passing the source to es module lexer you perhaps need to ensure the string is escaped into its JS string representation properly, or that may just be an artifact of the testing process too.

**Comment by drwpow** [comment]
Ah you’re right—I’m unable to recreate the parse error without the newlines. You’re right that this needs to be escaped before parsing. Appreciate you taking a look!
